### PR TITLE
Othello, Flappy clone

### PR DESCRIPTION
**Pull request by nenadalm**
Just a few more games I use. I found them using github search on `topic:pwa topic:game` (https://github.com/search?q=topic%3Agame+topic%3Apwa&type=repositories&s=updated&o=desc). There's more if you're interested, I just don't use them, so not adding them as I'm unsure on how well they work and how much useful they're, so not adding those.

### CODE REVIEW

**Review by notangelmario — CHANGES_REQUESTED** [review]
Hello! Author requirement has been changed. The `author` key is now required in all apps. Can you add them to the specs. It's enough to grab the name from the GitHub user.

**Review by notangelmario — CHANGES_REQUESTED** [review]
Also, the id is suffixed with `.json`. The filename extension should not be included in the `id` property.

**Comment by nenadalm** [comment]
remarks fixed.

**Review by notangelmario — APPROVED** [review]
Thanks for the changes! I will however fix a little bug in the update script before we merge this

**Pull request merged**
